// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";



// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Shopify",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CartProvider>
//           <Navbar />
//           <ShoppingCartModal />
//           {children}
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }


// import CartProvider from "./components/Providers";
// import Navbar from "./components/Navbar";
// import ShoppingCartModal from "./components/ShoppingCartModal";
// import Footer from "./components/Footer";
// import { type Metadata } from 'next'
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
// import { Inter, Roboto_Mono } from 'next/font/google'
// import './globals.css'

// const geistSans = Inter({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Roboto_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton />
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
            
//           </header>
//           {children}
//           <CartProvider>
//       <Navbar />
//        <ShoppingCartModal />
//         {children}
//          <Footer />
//          </CartProvider>
//         </body>
//       </html>
//     </ClerkProvider>
    
//   )
// }

import CartProvider from "./components/Providers";
import Navbar from "./components/Navbar";
import ShoppingCartModal from "./components/ShoppingCartModal";
import Footer from "./components/Footer";
import { type Metadata } from 'next'
import './globals.css'

import {
  ClerkProvider,

} from '@clerk/nextjs'
import { Inter, Roboto_Mono } from 'next/font/google'

const geistSans = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Roboto_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body >
          <CartProvider>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
             
            </header>
            <Navbar />
            <ShoppingCartModal />
            {children}
            <Footer />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}